Repository UniRegensburg/unsere-app-fur-die-universitat-regensburg-code-companion, pull requests merged in 2021-04, with the labels that each got.

#114 Check task items
  CodeCompanion/app/src/main/java/com/example/codecompanion/entity/Task.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/interfaces/ListTouchListener.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/interfaces/RecyclerViewClickListener.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/tasks/TasksFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/TaskManager.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/TaskViewAdapter.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/TinyDB.java
Labels: feature

#116 Reconencting bug
  Plugin/src/main/java/app/CCToolWindow.java
  Plugin/src/main/java/app/MessageHandler.java
  Plugin/src/main/java/app/WebRTC.java
  Plugin/src/main/java/app/services/application/ApplicationService.java
  TemplateProject/src/main.java
Labels: bug

#119 Profile refactoring
  CodeCompanion/app/src/main/res/drawable/ic_baseline_access_time_48.xml
  CodeCompanion/app/src/main/res/drawable/ic_baseline_code_48.xml
  CodeCompanion/app/src/main/res/drawable/ic_baseline_error_outline_48.xml
  CodeCompanion/app/src/main/res/drawable/ic_baseline_warning_amber_48.xml
  CodeCompanion/app/src/main/res/layout/fragment_compiler.xml
  CodeCompanion/app/src/main/res/layout/fragment_home.xml
  CodeCompanion/app/src/main/res/layout/fragment_profile.xml
  CodeCompanion/app/src/main/res/layout/fragment_tasks.xml
Labels: design, enhancement, feature

#125 Created tutorial and changed UI-Colors and some icons
  CodeCompanion/app/build.gradle
  CodeCompanion/app/src/main/AndroidManifest.xml
  CodeCompanion/app/src/main/java/com/example/codecompanion/SplashFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/onboarding/ViewPagerAdapter.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/onboarding/ViewPagerFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/onboarding/screens/FirstScreen.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/onboarding/screens/FourthScreen.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/onboarding/screens/SecondScreen.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/onboarding/screens/ThirdScreen.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/home/HomeFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/profile/ProfileFragment.java
  CodeCompanion/app/src/main/res/drawable/ic_baseline_cancel_24.xml
  CodeCompanion/app/src/main/res/drawable/ic_baseline_help_outline_24.xml
  CodeCompanion/app/src/main/res/drawable/ic_baseline_task_alt_24.xml
  CodeCompanion/app/src/main/res/drawable/ic_cc_nobackground.xml
  CodeCompanion/app/src/main/res/drawable/ic_coding.xml
  CodeCompanion/app/src/main/res/drawable/ic_coding_svgrepo_com.xml
  CodeCompanion/app/src/main/res/drawable/ic_intellij_idea_icon.xml
  CodeCompanion/app/src/main/res/drawable/ic_qr_code.xml
  CodeCompanion/app/src/main/res/layout/fragment_first_screen.xml
  CodeCompanion/app/src/main/res/layout/fragment_fourth_screen.xml
  CodeCompanion/app/src/main/res/layout/fragment_home.xml
  CodeCompanion/app/src/main/res/layout/fragment_profile.xml
  CodeCompanion/app/src/main/res/layout/fragment_second_screen.xml
  CodeCompanion/app/src/main/res/layout/fragment_splash.xml
  CodeCompanion/app/src/main/res/layout/fragment_third_screen.xml
  CodeCompanion/app/src/main/res/layout/fragment_view_pager.xml
  CodeCompanion/app/src/main/res/layout/rv_message_error.xml
  CodeCompanion/app/src/main/res/layout/rv_message_warning.xml
  CodeCompanion/app/src/main/res/layout/rv_task.xml
  CodeCompanion/app/src/main/res/navigation/mobile_navigation.xml
  CodeCompanion/app/src/main/res/values/colors.xml
  CodeCompanion/app/src/main/res/values/strings.xml
Labels: bug, feature

#122 [bugfix] Fixed font size in profile view
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/profile/ProfileFragment.java
  CodeCompanion/app/src/main/res/layout/fragment_profile.xml
Labels: bug

#129 [feature] link to google query from error description
  CodeCompanion/app/build.gradle
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/compiler/ExpandedMessageFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/AbstractCompilerMessageViewHolder.java
  CodeCompanion/app/src/main/res/layout/fragment_expanded_description.xml
  CodeCompanion/app/src/main/res/values/colors.xml
  CodeCompanion/app/src/main/res/values/strings.xml
  Plugin/src/main/java/app/MessageHandler.java
  Plugin/src/main/java/app/data/Const.java
  Plugin/src/main/java/app/services/application/ApplicationService.java
Labels: feature

#134 [bugfix] Let tasks checked while switching fragments
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/tasks/TasksFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/TaskViewAdapter.java
Labels: bug

#137 Comments added in app and plugin
  CodeCompanion/app/src/main/java/com/example/codecompanion/MainActivity.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/SplashFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/db/AppDatabase.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/db/ProjectInformation.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/entity/Task.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/interfaces/CustomPeerConnectionObserver.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/interfaces/ListTouchListener.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/models/CompilerMessage.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/models/CompilerMessageCatalogue.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/onboarding/ViewPagerAdapter.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/onboarding/ViewPagerFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/services/ErrorMessageReceiverService.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/services/LinesOfCodeMessageReceiverService.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/services/WebRTC.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/compiler/CompilerFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/compiler/ExpandedMessageFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/home/HomeFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/profile/ProfileFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/tasks/TasksFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/AbstractCompilerMessageViewHolder.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/ConnectionStateManager.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/DeadlineIntent.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/DeadlineReceiver.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/MessageManager.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/MessageViewAdapter.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/QrScanner.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/TaskManager.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/TaskViewAdapter.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/TimeSpentTimerTask.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/TinyDB.java
  Plugin/src/main/java/app/CCToolWindow.java
  Plugin/src/main/java/app/CCToolWindowFactory.java
  Plugin/src/main/java/app/ConnectionStateAction.java
  Plugin/src/main/java/app/ErrorMessage.java
  Plugin/src/main/java/app/MessageHandler.java
  Plugin/src/main/java/app/QRCodeGenerator.java
  Plugin/src/main/java/app/TaskHandler.java
  Plugin/src/main/java/app/WebRTC.java
  Plugin/src/main/java/app/listeners/ListenerHelper.java
Labels: enhancement
