Repository UniRegensburg/unsere-app-fur-die-universitat-regensburg-code-companion, pull requests merged in 2021-03, with the labels that each got.

#95 [feature] Tasks and Errors can now be sorted
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/compiler/CompilerFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/tasks/TasksFragment.java
Labels: feature

#99 Bottom navigation refactor
  CodeCompanion/app/src/main/java/com/example/codecompanion/MainActivity.java
  CodeCompanion/app/src/main/res/color/nav_view_item_selector.xml
  CodeCompanion/app/src/main/res/layout/activity_main.xml
  CodeCompanion/app/src/main/res/layout/fragment_home.xml
  CodeCompanion/app/src/main/res/layout/fragment_profile.xml
  CodeCompanion/app/src/main/res/layout/fragment_tasks.xml
  CodeCompanion/app/src/main/res/values/colors.xml
Labels: bug, enhancement

#103 [feature] Redesigned UI of connect, task and compiler fragment
  CodeCompanion/app/src/main/AndroidManifest.xml
  CodeCompanion/app/src/main/java/com/example/codecompanion/MainActivity.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/ui/home/HomeFragment.java
  CodeCompanion/app/src/main/java/com/example/codecompanion/util/TaskViewAdapter.java
  CodeCompanion/app/src/main/res/color/nav_view_item_selector.xml
  CodeCompanion/app/src/main/res/drawable/button_grey.xml
  CodeCompanion/app/src/main/res/drawable/ic_baseline_android_24.xml
  CodeCompanion/app/src/main/res/drawable/ic_baseline_error_outline_24.xml
  CodeCompanion/app/src/main/res/drawable/ic_baseline_warning_amber_24.xml
  CodeCompanion/app/src/main/res/drawable/message_error_template.xml
  CodeCompanion/app/src/main/res/drawable/message_warning_template.xml
  CodeCompanion/app/src/main/res/font/.xml
  CodeCompanion/app/src/main/res/layout/fragment_compiler.xml
  CodeCompanion/app/src/main/res/layout/fragment_home.xml
  CodeCompanion/app/src/main/res/layout/fragment_tasks.xml
  CodeCompanion/app/src/main/res/layout/rv_message_error.xml
  CodeCompanion/app/src/main/res/layout/rv_message_warning.xml
  CodeCompanion/app/src/main/res/layout/rv_task.xml
  CodeCompanion/app/src/main/res/values/colors.xml
  CodeCompanion/app/src/main/res/values/font_certs.xml
  CodeCompanion/app/src/main/res/values/preloaded_fonts.xml
  CodeCompanion/app/src/main/res/values/strings.xml
Labels: app, design, enhancement

#104 Added launcher icon and removed unused drawables
  CodeCompanion/app/src/main/AndroidManifest.xml
  CodeCompanion/app/src/main/ic_cc_launcher-playstore.png
  CodeCompanion/app/src/main/res/drawable-v24/ic_cc_foreground.xml
  CodeCompanion/app/src/main/res/drawable/color_gradient.xml
  CodeCompanion/app/src/main/res/drawable/comp_circular_progress_bar.xml
  CodeCompanion/app/src/main/res/drawable/comp_circular_progress_bar_background.xml
  CodeCompanion/app/src/main/res/drawable/ic_launcher_background.xml
  CodeCompanion/app/src/main/res/drawable/ic_launcher_foreground.xml
  CodeCompanion/app/src/main/res/drawable/user_icon_big.xml
  CodeCompanion/app/src/main/res/drawable/user_icon_img.xml
  CodeCompanion/app/src/main/res/mipmap-anydpi-v26/ic_cc_launcher.xml
  CodeCompanion/app/src/main/res/mipmap-anydpi-v26/ic_cc_launcher_round.xml
  CodeCompanion/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  CodeCompanion/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  CodeCompanion/app/src/main/res/mipmap-hdpi/ic_cc_launcher.png
  CodeCompanion/app/src/main/res/mipmap-hdpi/ic_cc_launcher_round.png
  CodeCompanion/app/src/main/res/mipmap-hdpi/ic_launcher.png
  CodeCompanion/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  CodeCompanion/app/src/main/res/mipmap-mdpi/ic_cc_launcher.png
  CodeCompanion/app/src/main/res/mipmap-mdpi/ic_cc_launcher_round.png
  CodeCompanion/app/src/main/res/mipmap-mdpi/ic_launcher.png
  CodeCompanion/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  CodeCompanion/app/src/main/res/mipmap-xhdpi/ic_cc_launcher.png
  CodeCompanion/app/src/main/res/mipmap-xhdpi/ic_cc_launcher_round.png
  CodeCompanion/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  CodeCompanion/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  CodeCompanion/app/src/main/res/mipmap-xxhdpi/ic_cc_launcher.png
  CodeCompanion/app/src/main/res/mipmap-xxhdpi/ic_cc_launcher_round.png
  CodeCompanion/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  CodeCompanion/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  CodeCompanion/app/src/main/res/mipmap-xxxhdpi/ic_cc_launcher.png
  CodeCompanion/app/src/main/res/mipmap-xxxhdpi/ic_cc_launcher_round.png
  CodeCompanion/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  CodeCompanion/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  CodeCompanion/app/src/main/res/values/ic_cc_background.xml
Labels: feature
